version: '3'
services:
  # https://bref.sh/docs/web-apps/local-development.html
  web:
    image: bref/fpm-dev-gateway
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - AWS_KEY=${AWS_KEY}
        - AWS_SECRET=${AWS_SECRET}
    ports:
      - '8000:80'
    volumes:
      - .:/var/task
    depends_on:
      - php
    environment:
      HANDLER: app/index.php
  php:
    image: bref/php-81-fpm-dev
    volumes:
      - .:/var/task:ro